# -*- coding: utf-8 -*-
"""PVT Extraction & Adjustment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A5QvpeD9IzivY2lgzUWoQ2wYfPuAdnd-

# **Summary of Oil PVT Study Results**
"""

# ── Summary of Oil PVT Study Results ──────────────────────────────────────────────
# All pressures in psia, temperatures in °F, GOR in scf/STB, API in degrees
reservoir_condition = {
    "well_name":       "NDI-OML-40 #22",
    "initial_pressure":  4089.7,   # psia  — initial reservoir pressure
    "initial_temp":      207.2,    # °F    — initial reservoir temperature
    "fluid_mol% C7+":             52.9,    # % - Reservoir fluid mol weight
    "fluid_mol_wt":     122.05,     # g/mol - Reservoir fluid mol weight
    "viscosity@initial_pressure":       0.989,     # cP - viscosity @ initial reservoir pressure @207.2°F
    "viscosity@Bp": 0.554,    # cP - viscosity @ Bubble point pressure @207.2°F

}

print("Reservoir_conditions loaded.")
print(f"  Well       : {reservoir_condition['well_name']}")
print(f"  Initial P    : {reservoir_condition['initial_pressure']} psia")
print(f"  Initial T    : {reservoir_condition['initial_temp']} °F")
print(f"  fluid_mol% C7+        : {reservoir_condition['fluid_mol% C7+']} %")
print(f"  fluid_mol_wt        : {reservoir_condition['fluid_mol_wt']} g/mol")
print(f"  viscosity@initial_pressure  : {reservoir_condition['viscosity@initial_pressure'] } cP")
print(f"  viscosity@Bp  : {reservoir_condition['viscosity@Bp'] } cP")

"""# **Separator test**"""

# ── Single Stage Separator test — list of seperator stage dictionaries ─────────────────────────────

separator_test = [
    {

        "test":         "1st Sep Test",
        "pressure":     215.0,   # psia
        "temperature":  90,   # °F
        "total GOR":          240.5,     # scf/STB
        "stock Tank API":     42.08,   # °API
        "formation vol factor": 1.1819
    },
    {

        "test":         "2nd Sep Test",
        "pressure":     130.0,   # psia
        "temperature":  90,   # °F
        "total GOR":          233.78,     # scf/STB
        "stock Tank API":     42.25,   # °API
        "formation vol factor": 1.1770
    },
    {

        "test":         "3rd Sep Test",
        "pressure":     102.0,   # psia
        "temperature":  90,   # °F
        "total GOR":          233.24,     # scf/STB
        "stock Tank API":     42.27,   # °API
        "formation vol factor": 1.1766
    },
    {

        "test":         "4th Sep Test",
        "pressure":     65,   # psia
        "temperature":  90,   # °F
        "total GOR":          238.28,     # scf/STB
        "stock Tank API":     42.14,   # °API
        "formation vol factor": 1.1805
     }
]

print(f"Separator test: {len(separator_test)} test defined.")
for s in separator_test:
    print(f"   {s['test']:15s}  P = {s['pressure']:7.1f} psia    T = {s['temperature']:.1f} °F    GOR = {s['total GOR']:.2f} scf/STB    stock Tank API = {s['stock Tank API']:.2f} °API    Bo = {s['formation vol factor']:.4f}")

separator_test[1]
pressure_value3 = separator_test[3]['pressure']
pressure_value3

"""# **Constant Composition Expansion (CCE)**"""

# ── Notes:  ¹ Gravimetric density at indicated T & P   |   ² Y-Function = [(Pb-P)/P] per [Relative Volume-1]   |   ³ Monophasic instantaneous compressibility at successive pressure steps ─────────────────────────────

CCE = {
        "pressure":     [5500,5000,4500,4090,3500,3000,2500,2000,1500,988,800,600,400,200],  # psia
        "relative volume":     [0.9524,0.9563,0.9610,0.9645,0.9705,0.9758,0.9815,0.9873,0.9935,1.0000,1.1037,1.3147,1.7978,3.4162
],
        "density":          [0.7663,0.7632,0.7595,0.7567,0.7520,0.7479,0.7436,0.7392,0.7346,0.7298,None,None,None,None],     # g/cm3
        "Y-function":     [None,None,None,None,None,None,None,None,None,None,2.2667,2.0547,1.8427,1.6307],    # -
        "compressibility": [8.320E-06,8.905E-06,9.477E-06,9.946E-06,1.060E-05,1.115E-05,1.169E-05,1.222E-05,1.274E-05,1.326E-05,None,None,None,None
]   # 1/psia
        }

CCE['compressibility'][0]
# print(f"Separator test: {len(separator_test)} test defined.")
# for s in separator_test:
#     print(f"   {s['test']:15s}  P = {s['pressure']:7.1f} psia    T = {s['temperature']:.1f} °F    GOR = {s['total GOR']:.2f} scf/STB    stock Tank API = {s['stock Tank API']:.2f} °API    Bo = {s['formation vol factor']:.4f}")

"""# **Differential Liberation Experiment (DLE)**"""

# ── Notes:  ¹ Scf/Stb: std cu ft of gas at 14.72 psia,60°F per bbl residual oil at 60°F   |   ² Bbl of oil + dissolved gas at indicated P&T per bbl residual oil at 60°F   |   ³ cu ft of gas at indicated P&T per std cu ft of gas at 14.72 psia,60°F   |   ⁴ Calculated using Lee-Gonzalez correlation ─────────────────────────────

DLE = {
        "pressure":     [5500,5000,4500,4090,3500,3000,2500,2000,1500,988,800,600,400,200,100,15
],  # psia
        "Rs":     [261.5,261.5,261.5,261.5,261.5,261.5,261.5,261.5,261.5,261.5,227.8,180.0,126.9,66.0,32.5,0.0
],  # Scf/Stb
        "Bo":          [1.159,1.163,1.169,1.173,1.181,1.187,1.194,1.201,1.209,1.217,1.208,1.188,1.162,1.120,1.093,1.066
],  # Bbl/Stb
        "Oil density":     [0.7663,0.7632,0.7595,0.7567,0.7520,0.7479,0.7436,0.7392,0.7346,0.7298,0.7353,0.7424,0.7502,0.7600,0.7654,0.7700
],  # g/cm3
        "Bg": [None,None,None,None,None,None,None,None,None,None,0.0217,0.0292,0.0444,0.0899,0.1804,1.2233
],  # cu ft/Scf
        "Gas Viscosity": [None,None,None,None,None,None,None,None,None,None,0.0139,0.0134,0.0128,0.0118,0.0106,0.0079
],  # cP
        "Gas Density": [None,None,None,None,None,None,None,None,None,None,0.0450,0.0345,0.0244,0.0146,0.0095,0.0026
],  # g/cc
        "Gas Z-factor": [None,None,None,None,None,None,None,None,None,None,0.9238,0.9327,0.9433,0.9554,0.9589,0.9752
]
}

len(DLE['Gas Z-factor'])